model:
  learning_task: LINK_PREDICTION
  encoder:
    layers:
      - - type: EMBEDDING
          output_dim: 3
  decoder:
    type: DISTMULT
    options:
      input_dim: 3
  loss:
    type: SOFTMAX_CE
    options:
      reduction: SUM
  dense_optimizer:
      type: ADAM
      options:
        learning_rate: 0.1
  sparse_optimizer:
      type: ADAGRAD
      options:
        learning_rate: 0.1
storage:
  device_type: cpu
  dataset:
    dataset_dir: ./datasets/fb15k_237_example/
  edges:
    type: HOST_MEMORY
  embeddings:
    type: HOST_MEMORY
  save_model: false
training:
  batch_size: 512
  negative_sampling:
    num_chunks: 1
    negatives_per_positive: -1
    degree_fraction: 0.0
    filtered: false
  num_epochs: 1
  pipeline:
    sync: true
  epochs_per_shuffle: 100
evaluation:
  epochs_per_eval: -1
#  batch_size: 1000
#  negative_sampling:
#    filtered: true
#  pipeline:
#    sync: true